name: Cleanup Actions History

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete runs older than 7 days
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cutoff=$(date -u -d "7 days ago" +"%Y-%m-%dT%H:%M:%SZ")

          gh api repos/${{ github.repository }}/actions/runs --paginate |
          jq -r --arg cutoff "$cutoff" '
            .workflow_runs[]
            | select(.created_at < $cutoff)
            | .id
          ' |
          while read id; do
            echo "Deleting $id"
            gh api \
              -X DELETE \
              repos/${{ github.repository }}/actions/runs/$id
          done
